name: Terraform plan for an environment.
on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: 'dev'
  workflow_dispatch:
    inputs:
      environment:
        required: false
        description: "Environment to deploy in"
        type: string
        default: 'dev'

jobs:
  continous_deployment:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan  -out "tfplan"
      - name: Update PR
        uses: actions/github-script@v7
        id: plan-comment
        with:
          environment: dev
          result-encoding: string
          script: |
            const { execSync } = require('child_process');
            const fs = require('fs');

            // Generate the plan output
            execSync('terraform show tfplan > ./plan_output.txt');
            execSync('cat ./plan_output.txt | sed -e \'s/\\x1b\\[[0-9;]*m//g\' > ./clean_plan_output.txt');

            // Read the cleaned plan output
            const planOutput = fs.readFileSync('clean_plan_output.txt', 'utf8');

            // Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Plan Output ' + core.getInput('environment', { required: true }))
            });

            const output = '#### Terraform Plan Output ' + core.getInput('environment', { required: true }) + '\n' +
              '```\n' +
              planOutput +
              '\n```\n';

            const outputLimitCharacters = 65000;
            let finalOutput;
            if (output.length > outputLimitCharacters) {
              const shortenedOutput = output.substring(0, outputLimitCharacters) + '...';
              finalOutput = `#### Terraform Plan is greater than ${outputLimitCharacters} characters this output has been shortened. \n` + shortenedOutput;
            } else {
              finalOutput = output;
            }

            // Delete previous comment so PR timeline makes sense
            if (botComment) {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
              });
            }

            // Create a new comment with the plan output
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: finalOutput
            });

            let PlanResult: string = '';
            if (! planOutput.includes('Your infrastructure matches the configuration')) {

              const regex = "Plan:.*\n";
              const matches = planOutput.match(regex);

              if (matches !== null && matches !== undefined && matches.length > 0) {
                PlanResult = matches[0];
              }
            }

            return PlanResult;
      - name: Plan Result (Post to teams)
        if: steps.plan-comment.outputs.result != ''
        run: echo "Posting to teams"
